version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin@!
      MYSQL_DATABASE: dice
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin@!
    container_name: dice_db
    ports:
      - '3306:3306'
    tty: true
