version: '3'
services:
  # server:
  #   image: d.sehyeon/dice
  #   container_name: server
  #   ports:
  #     - '4000:80'
  #   stdin_open: true
  # tty: true
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin@!
      MYSQL_DATABASE: dice
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin@!
    container_name: dice_db
    # network_mode: 'service:server'
    tty: true
    ports:
      - '3306:3306'
